package helper;

import calculator.Expression;
import calculator.IllegalConstruction;
import helper.antlr4.*;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.ParseTree;

public class MyExpressionParser {

    public static Expression parseExpression(String input) throws IllegalConstruction {
        ExpressionLexer lexer = new ExpressionLexer(CharStreams.fromString(input));

        // listener for the error of the lexer
        lexer.removeErrorListeners();
        lexer.addErrorListener(new MyExpressionErrorListener());

        CommonTokenStream tokens = new CommonTokenStream(lexer);
        ExpressionParser parser = new ExpressionParser(tokens);

        // listener for the error of the parser
        parser.removeErrorListeners();
        parser.addErrorListener(new MyExpressionErrorListener());

        // listener to the parser to build Expression object
        MyExpressionListener listener = new MyExpressionListener();
        parser.addParseListener(listener);

        try {
            parser.expr();
            // To show the parse tree generated by the parser
                //ParseTree tree = parser.expr();
                //System.out.println(tree.toStringTree(parser));
        } catch (RuntimeException e) {
            throw new IllegalConstruction();
        }

        // Return the result of the parsing
        return listener.getResult();
    }
}
