name: Code quality & coverage analysis
on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed # Runs after the worflow Java CI with Maven regardless of success or fail.

permissions:
  checks: write
  contents: write

jobs:
  coverage_and_quality:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Runs only on Java CI with Maven success

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }} # Pulls the commit associated with the triggering workflow

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: maven

      - name: Run Tests with JaCoCo
        run: mvn clean verify

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=ClementAllard_calculator-cucumber-2025-group-5 -Dsonar.organization=calculator-cucumber-group-5
