name: Code quality & coverage analysis
on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed # Runs after the worflow Java CI with Maven regardless of success or fail.

permissions:
  checks: write
  contents: write

jobs:
  coverage_and_quality:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Runs only on Java CI with Maven success

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout repository with full history
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }} # Pulls the commit associated with the triggering workflow
          fetch-depth: 0  # Fetch the entire history

      - name: Set up JDK 23
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: maven

      - name: Run Tests with JaCoCo
        run: mvn clean verify

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=ClementAllard_calculator-cucumber-2025-group-5 -Dsonar.organization=calculator-cucumber-group-5
