# Build and test a Java project with Maven, and compute and report test coverage 

name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_test:
    name: building, testing and quality analysis
    runs-on: ubuntu-latest

    permissions:
      # need write permissions for publishing the test report
      checks: write
      contents: write
      pull-requests: write

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - id: checkout
      name: checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
    - id: setupjava
      name: Set up with Java 23
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
      with:
        distribution: 'temurin'
        java-version: 23
        cache: 'maven'
        
    - id: mvn
      name: Build with Maven (including running all tests)
      run: mvn -B package --file pom.xml
      
    - id: testreport
      name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@1a128e49c0585bc0b8e38e541ac3b6e35a5bc727 # v1.9.0

    - id: uploadreport
      name: Upload Test Reports as Artifacts
      if: always()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: surefire-reports
        path: target/surefire-reports
        retention-days: 7
      
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@f33476a5a3fd5a4f77cb5eef2ebe728c1dd5b921 # v2.11.0
      with:
        generate-coverage-badge: true
        generate-branches-badge: true
        generate-summary: true

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
      with:
        default_author: github_actions
        message: 'commit badge'
        add: '*.svg'
