name: Reporting

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  generate-report:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: write
      actions: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Up Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '23'

      - id: mvn
        name: Build with Maven (including running all tests)
        run: xvfb-run mvn -B package --file pom.xml

      - id: testreport
        name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@1a128e49c0585bc0b8e38e541ac3b6e35a5bc727 # v1.9.0

      - id: uploadreport
        name: Upload Test Reports as Artifacts
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: surefire-reports
          path: target/surefire-reports
          retention-days: 7

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Run Code Coverage
        run: xvfb-run mvn test jacoco:report

      - name: Run Quality Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: xvfb-run mvn sonar:sonar -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} -Dsonar.organization=calculator-cucumber-group-5

      - name: Package Report
        run: |
          mkdir -p reports/quality
          cp -r target/surefire-reports reports/surefire-reports
          cp -r target/site/apidocs reports/javadoc
          cp -r target/site/jacoco reports/coverage
          cp -r target/site/sonar reports/quality
          zip -r report.zip reports

      - name: Attach Report to Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: report.zip