name: Reporting

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  generate-report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Download Test Reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: reports/tests

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Run Code Coverage
        run: mvn test jacoco:report

      - name: Run Quality Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=ClementAllard_calculator-cucumber-2025-group-5

      - name: Package Report
        run: |
          mkdir reports/quality
          cp -r target/site/apidocs reports/javadoc
          cp -r target/site/jacoco reports/coverage
          cp -r target/sonar reports/quality
          zip -r report.zip reports

      - name: Attach Report to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} report.zip